import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';

import ReactQueryClientProvider from '@/app/_components/provider/ReactQueryClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'jindevst portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="ko">
        <body className="w-full h-auto flex flex-col bg-[#171D25]">{children}</body>
      </html>
    </ReactQueryClientProvider>
  );
}
